export default `\
# deep-health — project configuration
# Generated by: deep-health init
#
# ecosystems: declarative list of ecosystems to scan and update.
#   Each entry configures the plugin, optional fixer strategy, validation commands, and advisors.
# protected_packages: packages that must NEVER be auto-upgraded beyond their stated constraint.
#   Any update requiring a constraint change needs explicit per-package authorization.
# safe_update_policy: patch/minor updates within existing constraints are auto-safe.

project:
  name: '{{projectName}}'
  client: '{{client}}'

# Declare ecosystems to scan and update.
# id must match a registered plugin (e.g. composer, npm).
# fixer: strategy id for automated remediation ('osv' (default) | 'npm-audit').
# validationCommands: commands to run after updates to verify correctness.
# advisors: commands to run for security/health analysis.
ecosystems:
{{#each ecosystems}}
  - id: '{{id}}'{{#if hasFixer}}
    fixer: '{{fixer}}'{{/if}}{{#if hasValidationCommands}}
    validationCommands:
{{#each validationCommands}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{/if}}{{#if hasAdvisors}}    advisors:
{{#each advisors}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{/if}}
{{/each}}
# Add packages that must not be auto-upgraded beyond their constraint.
protected_packages:
{{#each protectedPackageEcosystems}}
  {{#if active}}
  {{id}}:
    []
    # - package: '{{examplePackage}}'
    #   constraint: '{{exampleConstraint}}'
    #   reason: '{{exampleReason}}'
  {{else}}
  {{id}}: []
  {{/if}}
{{/each}}

safe_update_policy:
  allow_patch_and_minor_within_constraints: true
  require_authorization_for_constraint_change: true

conflict_resolution: 'stop_and_ask'

report_language: '{{reportLanguage}}'

{{#if hasOutputs}}
outputs:
  formats: [{{#each outputFormats}}'{{this}}'{{#unless @last}}, {{/unless}}{{/each}}]{{#if outputsDir}}
  dir: '{{outputsDir}}'{{/if}}
{{else}}
# outputs:                               # optional — output configuration
#   formats: ['markdown']
#   dir: '.deep-health/reports'
{{/if}}

{{#if enableSonarQube}}
scanners:
  sonarqube:
    enabled: true
    mode: 'external'
    host_url: 'http://localhost:9000'
    project_key: '{{sonarProjectKey}}'
    token_env: 'SONAR_TOKEN'
    on_failure: 'warn'
    # ce_task_timeout_seconds: 120     # optional — seconds to wait for Compute Engine task before
    #                                  #   fetching quality gate; 0 disables waiting (default: 120)
    # exclusions:                      # optional — sonar.exclusions glob patterns (full override)
    #   - 'node_modules/**'            #   When absent, ecosystem-specific defaults apply:
    #   - 'tests/**'                   #     npm:      node_modules/**, tests/**
    #   - 'dist/**'                    #     composer: vendor/**, tests/**
    # coverage_exclusions:             # optional — sonar.coverage.exclusions glob patterns
    #   - 'node_modules/**'
    #   - 'tests/**'
{{#if npmRuntimeVersion}}
  npm:
    runtime_version: '{{npmRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'node:{{npmRuntimeVersion}}'  # optional — override resolved Node image
{{/if}}
{{else}}
{{#if npmRuntimeVersion}}
scanners:
  npm:
    runtime_version: '{{npmRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'node:{{npmRuntimeVersion}}'  # optional — override resolved Node image
{{else}}
# scanners:                              # optional — additional scanner engines
#   sonarqube:
#     enabled: true
#     mode: 'external'
#     host_url: 'http://localhost:9000'
#     project_key: 'my-project'
#     token_env: 'SONAR_TOKEN'
#     on_failure: 'warn'
#     # ce_task_timeout_seconds: 120   # seconds to wait for CE task (0 = disable; default: 120)
#     # exclusions:                    # sonar.exclusions (full override; omit for ecosystem defaults)
#     #   - 'node_modules/**'
#     #   - 'tests/**'
#     # coverage_exclusions:           # sonar.coverage.exclusions (full override; omit for defaults)
#     #   - 'node_modules/**'
#     #   - 'tests/**'
#   osv:
#     runner: 'docker'                   # 'docker' (default) | 'local' | 'auto'
#                                        #   docker — always run via an ephemeral container (default)
#                                        #   local  — require a locally installed osv-scanner binary ⚠ warns
#                                        #   auto   — deprecated escape hatch ⚠ warns
#     image: 'ghcr.io/google/osv-scanner:latest'  # optional — Docker image override
#   npm:
#     mode: 'docker'                     # 'docker' (default) | 'local' | 'auto'
#                                        #   docker — run npm inside an ephemeral Node container (default)
#                                        #   local  — use the locally installed npm binary ⚠ warns
#                                        #   auto   — deprecated escape hatch ⚠ warns
#     runtime_version: '20'             # optional — Node version for Docker image resolution
#                                        #   Overrides inferVersion(); ignored when 'image' is set.
#     image: 'node:20'              # optional — override resolved Node image
{{/if}}
{{/if}}

# cloud_storage:                         # optional — upload reports to cloud storage after generation
#   provider: google_drive
#   folder_id: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'
#   credentials: '.deep-health/gdrive-service-account.json'
#   # credentials_env: GDRIVE_SERVICE_ACCOUNT_JSON  # alternative: env var with JSON (for CI/CD)
`;
