export default `\
# deep-health — project configuration
# Generated by: deep-health init
#
# ecosystems: declarative list of ecosystems to scan and update.
#   Each entry configures the plugin, optional fixer strategy, validation commands, and advisors.
#   Plugin ids: composer, npm, pip
# protected_packages: packages that must NEVER be auto-upgraded beyond their stated constraint.
#   Any update requiring a constraint change needs explicit per-package authorization.
# safe_update_policy: patch/minor updates within existing constraints are auto-safe.

project:
  name: '{{projectName}}'
  client: '{{client}}'

# Declare ecosystems to scan and update.
# id must match a registered plugin (e.g. composer, npm, pip).
# fixer: strategy id for automated remediation ('osv' (default) | 'npm-audit').
# validationCommands: commands to run after updates to verify correctness.
# advisors: commands to run for security/health analysis.
ecosystems:
{{#each ecosystems}}
  - id: '{{id}}'{{#if hasFixer}}
    fixer: '{{fixer}}'{{/if}}{{#if hasValidationCommands}}
    validationCommands:
{{#each validationCommands}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{/if}}{{#if hasAdvisors}}    advisors:
{{#each advisors}}      - name: '{{name}}'
        command: '{{command}}'
{{/each}}{{/if}}
{{/each}}
# Add packages that must not be auto-upgraded beyond their constraint.
protected_packages:
{{#each protectedPackageEcosystems}}
  {{#if active}}
  {{id}}:
    []
    # - package: '{{examplePackage}}'
    #   constraint: '{{exampleConstraint}}'
    #   reason: '{{exampleReason}}'
  {{else}}
  {{id}}: []
  {{/if}}
{{/each}}

safe_update_policy:
  allow_patch_and_minor_within_constraints: true
  require_authorization_for_constraint_change: true

conflict_resolution: 'stop_and_ask'

report_language: '{{reportLanguage}}'

{{#if hasOutputs}}
outputs:
  formats: [{{#each outputFormats}}'{{this}}'{{#unless @last}}, {{/unless}}{{/each}}]{{#if outputsDir}}
  dir: '{{outputsDir}}'{{/if}}
{{else}}
# outputs:                               # optional — output configuration
#   formats: ['markdown']
#   dir: '.deep-health/reports'
{{/if}}

{{#if enableSonarQube}}
scanners:
  sonarqube:
    enabled: true
    # mode: 'external' (default) — sonar.host.url and sonar.projectKey come from
    #       sonar-project.properties at your project root; SONAR_TOKEN env var
    #       provides auth.
    # mode: 'managed' — the CLI provisions an ephemeral SonarQube container via
    #       Docker, generates a token automatically, tears it down on exit.
    mode: 'external'
    on_failure: 'warn'
    # ce_task_timeout_seconds: 120     # optional — seconds to wait for Compute Engine task before
    #                                  #   fetching quality gate; 0 disables waiting (default: 120)
    # send_branch_name: false          # optional — forward git branch as -Dsonar.branch.name
    #                                  #   (requires SonarQube Developer Edition or higher)
    # scanner_image: 'sonarsource/sonar-scanner-cli:latest'  # optional — only used in managed mode
    #                                                        # when local sonar-scanner is unavailable
    #
    # NOTE: project_key, host_url, sources, exclusions, etc. live in sonar-project.properties.
    #       Run "deep-health init" (with SonarQube enabled) to generate a template if missing.
{{#if npmRuntimeVersion}}
  npm:
    runtime_version: '{{npmRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'node:{{npmRuntimeVersion}}'  # optional — override resolved Node image
{{/if}}
{{#if pipRuntimeVersion}}
  pip:
    runtime_version: '{{pipRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'python:{{pipRuntimeVersion}}-slim'  # optional — override resolved Python image
{{/if}}
{{else}}
{{#if npmRuntimeVersion}}
scanners:
  npm:
    runtime_version: '{{npmRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'node:{{npmRuntimeVersion}}'  # optional — override resolved Node image
{{#if pipRuntimeVersion}}
  pip:
    runtime_version: '{{pipRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'python:{{pipRuntimeVersion}}-slim'  # optional — override resolved Python image
{{/if}}
{{else}}
{{#if pipRuntimeVersion}}
scanners:
  pip:
    runtime_version: '{{pipRuntimeVersion}}'
    # mode: 'docker'                   # optional — 'docker' (default) | 'local' | 'auto'
    # image: 'python:{{pipRuntimeVersion}}-slim'  # optional — override resolved Python image
{{else}}
# scanners:                              # optional — additional scanner engines
#   sonarqube:
#     enabled: true
#     mode: 'external'                   # 'external' (default) | 'managed'
#     on_failure: 'warn'                 # 'warn' (default) | 'fail'
#     # ce_task_timeout_seconds: 120     # optional — seconds to wait for CE task (0 = disable; default: 120)
#     # send_branch_name: false          # optional — requires Developer Edition or higher
#     # scanner_image: 'sonarsource/sonar-scanner-cli:latest'  # optional — managed-mode container fallback
#     # project_key, host_url, exclusions, etc. live in sonar-project.properties.
#   osv:
#     runner: 'docker'                   # 'docker' (default) | 'local' | 'auto'
#                                        #   docker — always run via an ephemeral container (default)
#                                        #   local  — require a locally installed osv-scanner binary ⚠ warns
#                                        #   auto   — deprecated escape hatch ⚠ warns
#     image: 'ghcr.io/google/osv-scanner:latest'  # optional — Docker image override
#   npm:
#     mode: 'docker'                     # 'docker' (default) | 'local' | 'auto'
#                                        #   docker — run npm inside an ephemeral Node container (default)
#                                        #   local  — use the locally installed npm binary ⚠ warns
#                                        #   auto   — deprecated escape hatch ⚠ warns
#     runtime_version: '20'             # optional — Node version for Docker image resolution
#                                        #   Overrides inferVersion(); ignored when 'image' is set.
#     image: 'node:20'              # optional — override resolved Node image
#   pip:
#     mode: 'docker'                     # 'docker' (default) | 'local' | 'auto'
#                                        #   docker — run pip inside an ephemeral Python container (default)
#                                        #   local  — use the locally installed pip binary ⚠ warns
#                                        #   auto   — deprecated escape hatch ⚠ warns
#     runtime_version: '3.11'           # optional — Python version for Docker image resolution
#                                        #   Overrides inferVersion(); ignored when 'image' is set.
#     image: 'python:3.11-slim'         # optional — override resolved Python image
{{/if}}
{{/if}}
{{/if}}

# cloud_storage:                         # optional — upload reports to cloud storage after generation
#   provider: google_drive
#   folder_id: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'   # set automatically by 'deep-health cloud-setup'
#
# To connect Google Drive, run: deep-health cloud-setup
# Required environment variables (OAuth 2.0 Desktop app credentials from GCP Console):
#   DEEP_HEALTH_GOOGLE_CLIENT_ID=<your-oauth2-client-id>
#   DEEP_HEALTH_GOOGLE_CLIENT_SECRET=<your-oauth2-client-secret>
# Tokens are stored in: ~/.config/deep-health/tokens.json (chmod 600)
`;
