#!/usr/bin/env sh
# build-sea.sh — Build a Node.js SEA (Single Executable Application) binary.
#
# Usage:
#   CLI_NAME=deep-health TARGET_SUFFIX=linux-x64 ./scripts/build-sea.sh
#
# Environment variables:
#   CLI_NAME       — binary name (default: deep-health)
#   TARGET_SUFFIX  — platform suffix appended to binary (e.g. linux-x64, win-x64)
#
# Prerequisites:
#   - Node.js 26+
#   - dist-sea/deep-health.cjs  (built via: npm run build:sea-bundle)
#   - npx postject (installed via postject in devDependencies or npx on demand)
#
# The postject fuse sentinel NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
# must not be changed — it is the exact string Node.js looks for in the binary.

set -e

CLI_NAME="${CLI_NAME:-deep-health}"
TARGET_SUFFIX="${TARGET_SUFFIX:-linux-x64}"

BLOB="dist-sea/sea-prep.blob"
DIST_DIR="dist-bin"

# On Windows (MSYS/Git Bash/Cygwin), append .exe
case "$TARGET_SUFFIX" in
  win-*) EXT=".exe" ;;
  *)     EXT="" ;;
esac

OUT_BIN="${DIST_DIR}/${CLI_NAME}-${TARGET_SUFFIX}${EXT}"

# ------------------------------------------------------------------
# 1. Verify the SEA blob exists (generated by: npm run build:sea)
# ------------------------------------------------------------------
if [ ! -f "${BLOB}" ]; then
  echo "Error: SEA blob not found at ${BLOB}." >&2
  echo "Run 'npm run build:sea' to generate it before calling this script." >&2
  exit 1
fi

# ------------------------------------------------------------------
# 2. Create dist-bin/ and copy the node binary
# ------------------------------------------------------------------
mkdir -p "${DIST_DIR}"

NODE_BIN="$(command -v node)"
echo "Copying node binary from ${NODE_BIN} to ${OUT_BIN} ..."
cp "${NODE_BIN}" "${OUT_BIN}"

# ------------------------------------------------------------------
# 3. macOS: strip existing code signature before injection
# ------------------------------------------------------------------
OS="$(uname -s 2>/dev/null || echo Unknown)"
if [ "$OS" = "Darwin" ]; then
  echo "macOS detected — removing existing code signature ..."
  codesign --remove-signature "${OUT_BIN}"
fi

# ------------------------------------------------------------------
# 4. Inject the SEA blob using postject
# ------------------------------------------------------------------
echo "Injecting SEA blob into ${OUT_BIN} ..."

if [ "$OS" = "Darwin" ]; then
  npx postject "${OUT_BIN}" NODE_SEA_BLOB "${BLOB}" \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    --macho-segment-name NODE_SEA
else
  npx postject "${OUT_BIN}" NODE_SEA_BLOB "${BLOB}" \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
fi

# ------------------------------------------------------------------
# 5. macOS: re-sign the binary after injection
# ------------------------------------------------------------------
if [ "$OS" = "Darwin" ]; then
  echo "Re-signing binary with ad-hoc signature ..."
  codesign --sign - "${OUT_BIN}"
fi

echo "Done: ${OUT_BIN}"
